#!/usr/bin/env python3
"""
Register (or show, check, remove) the paynani plugin for OpenCode.

OpenCode loads every file in its global `plugins/` directory at startup. This
script writes one small file there, `paynani.js`, that re-exports the plugin
from this clone, so an upgrade of the clone is picked up without re-registering.
It never edits `opencode.json`: that file belongs to the person using OpenCode.

The generated file exports exactly one name. OpenCode calls every export of a
plugin file as a plugin and refuses the file if one of them is not a function,
so re-exporting the whole module would break it.

Usage:
  opencode_plugin.py --print       show the file, change nothing
  opencode_plugin.py --check       report whether it is registered
  opencode_plugin.py --install     write it, backing up a different file first
  opencode_plugin.py --uninstall   remove it, only if paynani wrote it
"""

import argparse
import json
import os
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PLUGIN = ROOT / "harness" / "opencode" / "paynani.js"
FILE_NAME = "paynani.js"
HEADER = "// Generated by paynani scripts/opencode_plugin.py. Re-run it rather than editing.\n"


def config_dir():
    explicit = os.environ.get("OPENCODE_CONFIG_DIR", "").strip()
    if explicit:
        return pathlib.Path(explicit).expanduser()
    xdg = os.environ.get("XDG_CONFIG_HOME", "").strip()
    base = pathlib.Path(xdg).expanduser() if xdg else pathlib.Path.home() / ".config"
    return base / "opencode"


def default_target():
    return config_dir() / "plugins" / FILE_NAME


def content():
    return (
        HEADER
        + "// OpenCode calls every export of a plugin file as a plugin, so this file\n"
        + "// exports exactly one.\n"
        + f"export {{ PaynaniPlugin }} from {json.dumps(str(PLUGIN))}\n"
    )


def read(path):
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise SystemExit(f"cannot read {path}: {exc}")


def install(path):
    wanted = content()
    current = read(path)
    if current == wanted:
        print(f"already registered in {path}; nothing to do")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    if current is not None:
        backup = path.with_name(path.name + ".paynani.bak")
        shutil.copy2(path, backup)
        print(f"backed up {path} to {backup}")
    tmp = path.with_name(path.name + ".paynani.tmp")
    with open(tmp, "w", encoding="utf-8") as handle:
        handle.write(wanted)
        handle.flush()
        os.fsync(handle.fileno())
    tmp.replace(path)
    print(f"registered the paynani OpenCode plugin in {path}")
    return 0


def uninstall(path):
    current = read(path)
    if current is None:
        print(f"not registered in {path}; nothing to do")
        return 0
    if not current.startswith(HEADER):
        print(f"{path} was not written by paynani; left it in place", file=sys.stderr)
        return 1
    path.unlink()
    print(f"removed the paynani OpenCode plugin from {path}")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--print", action="store_true", dest="show")
    group.add_argument("--check", action="store_true")
    group.add_argument("--install", action="store_true")
    group.add_argument("--uninstall", action="store_true")
    parser.add_argument("--target", default=None,
                        help="plugin file to act on (default: $OPENCODE_CONFIG_DIR/plugins/"
                             "paynani.js or ~/.config/opencode/plugins/paynani.js)")
    args = parser.parse_args()
    path = pathlib.Path(args.target).expanduser() if args.target else default_target()

    if args.show:
        print(f"# {path}")
        print(content(), end="")
        return 0
    if args.check:
        if read(path) == content():
            print(f"registered in {path}")
            return 0
        print(f"NOT registered in {path}")
        return 1
    if args.install:
        return install(path)
    return uninstall(path)


if __name__ == "__main__":
    sys.exit(main())
